# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 650)
        MainWindow.setStyleSheet("\n"
"    QMainWindow {\n"
"        background-color: #f0f2f5; /* Light gray background */\n"
"    }\n"
"    QLabel#label { /* Title label */\n"
"        color: #333333;\n"
"        font-size: 30pt;\n"
"        font-weight: bold;\n"
"        padding: 10px;\n"
"    }\n"
"    QGroupBox {\n"
"        border: 1px solid #dcdcdc;\n"
"        border-radius: 8px;\n"
"        margin-top: 10px;\n"
"        background-color: #ffffff;\n"
"        padding: 15px;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top center;\n"
"        padding: 0 10px;\n"
"        background-color: #e0e0e0;\n"
"        border-radius: 5px;\n"
"        font-weight: bold;\n"
"        color: #555555;\n"
"    }\n"
"    QTextEdit, QLineEdit {\n"
"        border: 1px solid #cccccc;\n"
"        border-radius: 5px;\n"
"        padding: 8px;\n"
"        background-color: #fcfcfc;\n"
"        font-size: 10pt;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: #007bff; /* Primary blue */\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"        padding: 10px 20px;\n"
"        font-size: 10pt;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #0056b3; /* Darker blue on hover */\n"
"    }\n"
"    QPushButton#btn_gen_keys {\n"
"        background-color: #28a745; /* Green for generate */\n"
"    }\n"
"    QPushButton#btn_gen_keys:hover {\n"
"        background-color: #218838;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_main.addWidget(self.label)
        self.horizontalLayout_top_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top_buttons.setSpacing(10)
        self.horizontalLayout_top_buttons.setObjectName("horizontalLayout_top_buttons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_top_buttons.addItem(spacerItem)
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.horizontalLayout_top_buttons.addWidget(self.btn_gen_keys)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_top_buttons.addItem(spacerItem1)
        self.verticalLayout_main.addLayout(self.horizontalLayout_top_buttons)
        self.horizontalLayout_content = QtWidgets.QHBoxLayout()
        self.horizontalLayout_content.setSpacing(20)
        self.horizontalLayout_content.setObjectName("horizontalLayout_content")
        self.groupBox_cipher = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_cipher.setObjectName("groupBox_cipher")
        self.verticalLayout_cipher = QtWidgets.QVBoxLayout(self.groupBox_cipher)
        self.verticalLayout_cipher.setSpacing(10)
        self.verticalLayout_cipher.setObjectName("verticalLayout_cipher")
        self.label_2 = QtWidgets.QLabel(self.groupBox_cipher)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_cipher.addWidget(self.label_2)
        self.txt_plain_text = QtWidgets.QTextEdit(self.groupBox_cipher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txt_plain_text.sizePolicy().hasHeightForWidth())
        self.txt_plain_text.setSizePolicy(sizePolicy)
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.verticalLayout_cipher.addWidget(self.txt_plain_text)
        self.horizontalLayout_cipher_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_cipher_buttons.setSpacing(10)
        self.horizontalLayout_cipher_buttons.setObjectName("horizontalLayout_cipher_buttons")
        self.btn_encrypt = QtWidgets.QPushButton(self.groupBox_cipher)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.horizontalLayout_cipher_buttons.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.groupBox_cipher)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.horizontalLayout_cipher_buttons.addWidget(self.btn_decrypt)
        self.verticalLayout_cipher.addLayout(self.horizontalLayout_cipher_buttons)
        self.label_3 = QtWidgets.QLabel(self.groupBox_cipher)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_cipher.addWidget(self.label_3)
        self.txt_cipher_text = QtWidgets.QTextEdit(self.groupBox_cipher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txt_cipher_text.sizePolicy().hasHeightForWidth())
        self.txt_cipher_text.setSizePolicy(sizePolicy)
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.verticalLayout_cipher.addWidget(self.txt_cipher_text)
        self.horizontalLayout_content.addWidget(self.groupBox_cipher)
        self.groupBox_signature = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_signature.setObjectName("groupBox_signature")
        self.verticalLayout_signature = QtWidgets.QVBoxLayout(self.groupBox_signature)
        self.verticalLayout_signature.setSpacing(10)
        self.verticalLayout_signature.setObjectName("verticalLayout_signature")
        self.label_4 = QtWidgets.QLabel(self.groupBox_signature)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_signature.addWidget(self.label_4)
        self.txt_info = QtWidgets.QTextEdit(self.groupBox_signature)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txt_info.sizePolicy().hasHeightForWidth())
        self.txt_info.setSizePolicy(sizePolicy)
        self.txt_info.setObjectName("txt_info")
        self.verticalLayout_signature.addWidget(self.txt_info)
        self.horizontalLayout_signature_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_signature_buttons.setSpacing(10)
        self.horizontalLayout_signature_buttons.setObjectName("horizontalLayout_signature_buttons")
        self.btn_sign = QtWidgets.QPushButton(self.groupBox_signature)
        self.btn_sign.setObjectName("btn_sign")
        self.horizontalLayout_signature_buttons.addWidget(self.btn_sign)
        self.btn_verify = QtWidgets.QPushButton(self.groupBox_signature)
        self.btn_verify.setObjectName("btn_verify")
        self.horizontalLayout_signature_buttons.addWidget(self.btn_verify)
        self.verticalLayout_signature.addLayout(self.horizontalLayout_signature_buttons)
        self.label_5 = QtWidgets.QLabel(self.groupBox_signature)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_signature.addWidget(self.label_5)
        self.txt_sign = QtWidgets.QTextEdit(self.groupBox_signature)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txt_sign.sizePolicy().hasHeightForWidth())
        self.txt_sign.setSizePolicy(sizePolicy)
        self.txt_sign.setObjectName("txt_sign")
        self.verticalLayout_signature.addWidget(self.txt_sign)
        self.horizontalLayout_content.addWidget(self.groupBox_signature)
        self.verticalLayout_main.addLayout(self.horizontalLayout_content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Cipher Application"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">RSA_CIPHER</span></p></body></html>"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate Keys"))
        self.groupBox_cipher.setTitle(_translate("MainWindow", "Encryption / Decryption"))
        self.label_2.setText(_translate("MainWindow", "Plain Text"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.groupBox_signature.setTitle(_translate("MainWindow", "Signing / Verification"))
        self.label_4.setText(_translate("MainWindow", "Information / Message to Sign"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.label_5.setText(_translate("MainWindow", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
